<?php include 'includes/head.php'; ?>
<?php include 'includes/navigation.php'; ?>
<?php include 'includes/hero.php'; ?>
<?php include 'includes/about.php'; ?>
<?php include 'includes/experience.php'; ?>
<?php include 'includes/events.php'; ?>
<?php include 'includes/gallery.php'; ?>
<?php include 'includes/contact.php'; ?>
<?php include 'includes/whatsapp-button.php'; ?>
<?php include 'includes/booking-dialog.php'; ?>
<?php include 'includes/footer.php'; ?>
